spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  application:
    name: gulimail-member
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
server:
  port: 8000
logging:
  level:
    com.heng.gulimall: debug

